name: Build and deploy production

on:
  workflow_dispatch:

jobs:
  frontend:
    environment: production
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/frontend
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
        with:
          WORK_DIR: '${{env.working-directory}}'
          REACT_APP_SELECTED_ENVIRONMENT: production
      - name: Deploy to AWS S3
        uses: ./.github/actions/deploy
        with:
          S3_BUCKET: '${{secrets.S3_BUCKET}}'
          S3_PREFIX: '/'
          AWS_ACCESS_KEY_ID: '${{secrets.AWS_ACCESS_KEY_ID}}'
          AWS_SECRET_ACCESS_KEY: '${{secrets.AWS_SECRET_ACCESS_KEY}}'
          AWS_REGION: '${{secrets.AWS_REGION}}'
          WORK_DIR: '${{env.working-directory}}'
